=== uo265578/xml/XML/Ejercicio-1/Tarea-2/estudiantes.dtd
<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (datos,(estudiante,estudiante,estudiante)?)>
<!ELEMENT datos (nombre, apellido, fecha_nacimiento, lugar_nacimiento, coordenadas_nacimiento, lugar_residencia, coordenadas_residencia, fotografias+, videos*, comentario)>


<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT lugar_nacimiento (#PCDATA)>
<!ELEMENT lugar_residencia (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

<!ELEMENT fotografias (foto)+>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto url CDATA #REQUIRED>

<!ELEMENT videos (video)*>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video url CDATA #REQUIRED>

<!ELEMENT coordenadas_nacimiento (latitud,longitud,altitud)>
<!ELEMENT coordenadas_residencia (latitud,longitud,altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

=== uo265578/xml/XML/Ejercicio-1/Tarea-2/estudiantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudiantes SYSTEM "estudiantes.dtd">
<estudiantes> 
	<estudiante>
		<datos>
			<nombre>Juan</nombre>
			<apellido>Cuesta</apellido>
			<fecha_nacimiento>1957-11-03</fecha_nacimiento>
			<lugar_nacimiento>Ribadesella</lugar_nacimiento>
			<coordenadas_nacimiento>
				<latitud>43.46321395964228</latitud>
				<longitud>-5.056486546343498</longitud>
				<altitud>95.6587</altitud>
			</coordenadas_nacimiento>
			<lugar_residencia>Ribadesella</lugar_residencia>
			<coordenadas_residencia>
				<latitud>43.46321395964228</latitud>
				<longitud>-5.056486546343498</longitud>
				<altitud>89.6587</altitud>
			</coordenadas_residencia>
			<fotografias>
				<foto url="https://anhqv.es/wp-content/uploads/2015/09/59360_jose-luis-gil-interprete-de-juan-cuesta-en-aqui-no-hay-quien-viva-e1512895385871.jpg"></foto>
			</fotografias>
			<videos>
				<video url="https://www.youtube.com/watch?v=az9EccMMhz0"></video>
			</videos>
			<comentario>
				Presidente de la comunidad y vecino del segundo A
			</comentario>
		</datos>
			<!--AMIGO 1-->
			<estudiante>
				<datos>
					<nombre>Emilio</nombre>
					<apellido>Delgado</apellido>
					<fecha_nacimiento>1969-05-13</fecha_nacimiento>
					<lugar_nacimiento>Arriondas</lugar_nacimiento>
					<coordenadas_nacimiento>
						<latitud>43.38093868770556</latitud>
						<longitud>-5.184301148160496</longitud>
						<altitud>100.6587</altitud>
					</coordenadas_nacimiento>
					<lugar_residencia>Llanes</lugar_residencia>
					<coordenadas_residencia>
						<latitud>43.410060612621095</latitud>
						<longitud>-4.749607444078907</longitud>
						<altitud>10.265</altitud>
					</coordenadas_residencia>
					<fotografias>
						<foto url="https://cope-cdnmed.agilecontent.com/resources/jpg/2/2/1640843136622.jpg"></foto>
					</fotografias>
					<videos>
						<video url= "https://www.youtube.com/watch?v=fG9eVtLxQa4"></video>
					</videos>
					<comentario>
						Portero de la comunidad, vive en la porteria.
					</comentario>
				</datos>
					<!--AMIGO 1.1-->
					<estudiante>
						<datos>
							<nombre>Roberto</nombre>
							<apellido>Alonso</apellido>
							<fecha_nacimiento>1987-08-20</fecha_nacimiento>
							<lugar_nacimiento>Oviedo</lugar_nacimiento>
							<coordenadas_nacimiento>
								<latitud>43.356558980153345</latitud>
								<longitud>-5.839103308444676</longitud>
								<altitud>100.6587</altitud>
							</coordenadas_nacimiento>
							<lugar_residencia>Oviedo</lugar_residencia>
							<coordenadas_residencia>
								<latitud>43.34676927004314</latitud>
								<longitud>-5.836298506660003</longitud>
								<altitud>900.545</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="http://i.imgur.com/oQUEQF0.jpg"></foto>
							</fotografias>
							<videos>
								<video url="https://www.youtube.com/watch?v=9XIpteVPMq4"></video>
							</videos>
							<comentario>
								Pintor de cuadros, vive en el tercero A.
							</comentario>
						</datos>

					</estudiante>
					<!--AMIGO 1.2-->
					<estudiante>
						<datos>
							<nombre>Mariano</nombre>
							<apellido>Delgado</apellido>
							<fecha_nacimiento>1950-11-23</fecha_nacimiento>
							<lugar_nacimiento>Arriondas</lugar_nacimiento>
					<coordenadas_nacimiento>
						<latitud>43.38093868770556</latitud>
						<longitud>-5.184301148160496</longitud>
						<altitud>50.6587</altitud>
					</coordenadas_nacimiento>
							<lugar_residencia>Llanes</lugar_residencia>
							<coordenadas_residencia>
								<latitud>43.39675335470032</latitud>
								<longitud>-4.741818476945724</longitud>
								<altitud>10.78651</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="https://cope-cdnmed.agilecontent.com/resources/jpg/2/2/1640843136622.jpg"></foto>
							</fotografias>
							<videos>
								<video url="https://www.youtube.com/watch?v=Aev9q0RwYUY"></video>
							</videos>
							<comentario>
								Padre de Emilio, viven en la porteria.
							</comentario>
						</datos>
					</estudiante>
					<!--AMIGO 1.3-->
					<estudiante>
						<datos>
							<nombre>Paco</nombre>
							<apellido>Ortega</apellido>
							<fecha_nacimiento>1979-10-03</fecha_nacimiento>
							<lugar_nacimiento>Gijón</lugar_nacimiento>
							<coordenadas_nacimiento>
								<latitud>43.53266763365407</latitud>
								<longitud>-5.659528822102597</longitud>
								<altitud>15.54151</altitud>
							</coordenadas_nacimiento>
							<lugar_residencia>Luanco</lugar_residencia>
							<coordenadas_residencia>
								<latitud>43.53914484702363</latitud>
								<longitud>-5.661763111002195</longitud>
								<altitud>15.984</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="https://www.cabroworld.com/wp-content/uploads/2021/10/guillermo-portada.jpg"></foto>
							</fotografias>
							<videos>
								<video url="https://www.youtube.com/watch?v=cWe7zJ5QGwo"></video>
							</videos>
							<comentario>
								Encargado del videoclub, vive en otro edificio.
							</comentario>
						</datos>
					</estudiante>

			</estudiante>
			<!--AMIGO 2-->
			<estudiante>
				<datos>
					<nombre>Marisa</nombre>
					<apellido>Benito</apellido>
					<fecha_nacimiento>1960-08-07</fecha_nacimiento>
					<lugar_nacimiento>Vigo</lugar_nacimiento>
					<coordenadas_nacimiento>
						<latitud>42.23429553952388</latitud>
						<longitud>-8.727514525588557</longitud>
						<altitud>15.6587</altitud>
					</coordenadas_nacimiento>
					<lugar_residencia>Vigo</lugar_residencia>
					<coordenadas_residencia>
						<latitud>42.232892042511</latitud>
						<longitud>-8.687394652920368</longitud>
						<altitud>15.984</altitud>
					</coordenadas_residencia>
					<fotografias>
						<foto url="https://imagenes.lainformacion.com/files/image_656_370/uploads/imagenes/2013/04/03/muere-marivi-bilbao.jpg"></foto>
					</fotografias>
					<videos>
						<video url="https://www.youtube.com/watch?v=WM3kyn5D4f4"></video>
					</videos>
					<comentario>
						Jubilada y aficionada al bingo, vive en el primero A.
					</comentario>
				</datos>
					<!--AMIGO 1-->
					<estudiante>
						<datos>
							<nombre>Concha</nombre>
							<apellido>Penella</apellido>
							<fecha_nacimiento>1962-05-29</fecha_nacimiento>
							<lugar_nacimiento>Ourense</lugar_nacimiento>
							<coordenadas_nacimiento>
								<latitud>42.33589427047176</latitud>
								<longitud>-7.869819610622399</longitud>
								<altitud>194.78651</altitud>
							</coordenadas_nacimiento>
							<lugar_residencia>Ourense</lugar_residencia>
							<coordenadas_residencia>
								<latitud>42.32660842438522</latitud>
								<longitud>-7.888193555351435</longitud>
								<altitud>196.78651</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="https://phantom-elmundo.unidadeditorial.es/f0bbf44d03874c0352b724df43f6e232/assets/multimedia/imagenes/2020/05/01/15883468437572.jpg"></foto>
							</fotografias>
							<videos>
								<video url= "https://www.youtube.com/watch?v=wkZaZA6iBQU"></video>
							</videos>
							<comentario>
								Amiga de Marisa, viven juntas en el primero A.
							</comentario>
						</datos>
					</estudiante>
					<!--AMIGO 2-->
					<estudiante>
						<datos>
							<nombre>Vicenta</nombre>
							<apellido>Benito</apellido>
							<fecha_nacimiento>1965-01-27</fecha_nacimiento>
							<lugar_nacimiento>Pontevedra</lugar_nacimiento>
							<coordenadas_nacimiento>
								<latitud>42.42759661259383</latitud>
								<longitud>-8.663916510187162</longitud>
								<altitud>27.6587</altitud>
							</coordenadas_nacimiento>
							<lugar_residencia>Pontevedra</lugar_residencia>
							<coordenadas_residencia>
								<latitud>42.43430606228051</latitud>
								<longitud>-8.623284372994613</longitud>
								<altitud>29.984</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="https://filesedc.com/uploads/17/img/2022/01/1200/imatge-de-lactriu-gemma-cuervo-vicenta-a-aqui-no-hay-quien-viva-amb-cook-el-gosset-de-vicenta-61ee5138af66f.webp"></foto>
							</fotografias>
							<videos>
								<video url="https://www.youtube.com/watch?v=ez2rUGnvaxg"></video>
							</videos>
							<comentario>
								Hermana pequeña de Marisa, viven juntas en el primero A.
							</comentario>
						</datos>
					</estudiante>
					<!--AMIGO 3-->
					<estudiante>
						<datos>
							<nombre>Paloma</nombre>
							<apellido>Hurtado</apellido>
							<fecha_nacimiento>1966-02-25</fecha_nacimiento>
							<lugar_nacimiento>Salamanca</lugar_nacimiento>
							<coordenadas_nacimiento>
								<latitud>40.960976368818635</latitud>
								<longitud>-5.664488766771246</longitud>
								<altitud>230.285784</altitud>
							</coordenadas_nacimiento>
							<lugar_residencia>Valladolid</lugar_residencia>
							<coordenadas_residencia>
								<latitud>41.665168773068224</latitud>
								<longitud>-4.76146222698356</longitud>
								<altitud>210.875454/</altitud>
							</coordenadas_residencia>
							<fotografias>
								<foto url="https://imagenes.20minutos.es/files/image_990_v3/uploads/imagenes/2022/03/08/loles-leon-como-paloma-cuesta.jpeg"></foto>
							</fotografias>
							<videos>
								<video url="https://www.youtube.com/watch?v=vH9GeF6eaT4"></video>
							</videos>
							<comentario>
								Mujer de Juan Cuesta, viven juntos en el segundo A.
							</comentario>
						</datos>
					</estudiante>
			</estudiante>
			<!--AMIGO 3-->
			<estudiante>
				<datos>
					<nombre>Belén</nombre>
					<apellido>Lopez</apellido>
					<fecha_nacimiento>1977-11-12</fecha_nacimiento>
					<lugar_nacimiento>León</lugar_nacimiento>
